services:
  db:
    image: postgres:15.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=jijij;oi**
      - POSTGRES_DB=spacex
      - NODE_ENV=development
    ports:
      - "5433:5432"
  api:
    image: node:16-alpine
    command: sh -c "npm i && npx prisma migrate dev && npx nodemon index.js"
    ports:
      - 5000:5000
    working_dir: /api
    volumes:
      - ./api:/api
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:jijij;oi**@db:5432/spacex?schema=public
    depends_on: [db]
  client:
    image: node:16-alpine
    command: sh -c "npm i && npm start"
    ports:
      - 3000:3000
    working_dir: /client
    environment:
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    volumes:
      - ./client:/client
    depends_on: [api]
